# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[ns2kracy/mobot/log]'
  director: 'log/logs'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# system configuration
system:
  host: '127.0.0.1'
  port: '6000'
  ws_port: "5700"
  db-type: 'mysql'
  use-redis: false     # 使用redis
  use-multipoint: false

# mysql connect configuration
mysql:
  path: '139.224.19.236'
  port: '3306'
  database: 'mobot'
  driver: 'mysql'
  config: 'charset=utf8&parseTime=True&loc=Local'
  username: 'root'
  password: '123456'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: "debug"
  log-zap: false
